export const CHANNELS_LOADING = 'CHANNELS_LOADING';
export const CHANNELS_FAILED = 'CHANNELS_FAILED';
export const ADD_CHANNELS = 'ADD_CHANNELS';
export const TOGGLE_CHANNELS = 'TOGGLE_CHANNELS';
export const ADD_CHANNEL_DROPS = 'ADD_CHANNEL_DROPS';
export const ADD_CHANNEL_REPLACEMENTS = 'ADD_CHANNEL_REPLACEMENTS';
export const ADD_CHANNEL_WHITELIST = 'ADD_CHANNEL_WHITELIST';
export const REMOVE_CHANNEL_DROPS = 'REMOVE_CHANNEL_DROPS';
export const REMOVE_CHANNEL_REPLACEMENTS = 'REMOVE_CHANNEL_REPLACEMENTS';
export const REMOVE_CHANNEL_WHITELIST = 'REMOVE_CHANNEL_WHITELIST';
export const EDIT_CHANNEL_DROPS = 'EDIT_CHANNEL_DROPS';
export const EDIT_CHANNEL_REPLACEMENTS = 'EDIT_CHANNEL_REPLACEMENTS';
export const EDIT_CHANNEL_WHITELIST = 'EDIT_CHANNEL_WHITELIST';

export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_FAILED = 'MESSAGES_FAILED';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const PAGE_MESSAGES = 'PAGE_MESSAGES';
export const TAB_MESSAGES = 'TAB_MESSAGES';

export const FEEDS_LOADING = 'FEEDS_LOADING';
export const FEEDS_FAILED = 'FEEDS_FAILED';
export const ADD_FEEDS = 'ADD_FEEDS';
export const TOGGLE_FEEDS = 'TOGGLE_FEEDS';

export const GLOBAL_LOADING = 'GLOBAL_LOADING';
export const GLOBAL_FAILED = 'GLOBAL_FAILED';
export const ADD_GLOBAL = 'ADD_GLOBAL';
export const TOGGLE_GLOBAL = 'TOGGLE_GLOBAL';

export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const ACCOUNTS_FAILED = 'ACCOUNTS_FAILED';
export const ADD_ACCOUNTS = 'ADD_ACCOUNTS';
export const TOGGLE_ACCOUNTS = 'TOGGLE_ACCOUNTS';
